repos:
-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.16.0
    hooks:
    - id: check-github-workflows
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
    - id: shellcheck
      types: [shell]
