name: bootstrap
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bootstrap:
    runs-on: macos-latest
    timeout-minutes: 45
    name: "bootstrap"
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: on
      # Make the environment more similar to what Mac defaults to
      SHELL: /bin/zsh

    steps:
      - uses: actions/checkout@v2

      - name: Execute bootstrap
        run: |
          ./uninstall.sh
          ./bootstrap.sh
