name: bootstrap
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dev-env-cli:
    runs-on: macos-latest
    timeout-minutes: 20
    env:
      STRAP_CI: 1

    steps:
      - uses: actions/checkout@v2

      - name: Execute bootstrap
        run: |
          ./bootstrap.sh
