name: bootstrap
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fast-bootstrap:
    runs-on: macos-13
    timeout-minutes: 30
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: on
      # Make the environment more similar to what Mac defaults to
      SHELL: /bin/zsh

    steps:
      - uses: actions/checkout@v3

      - name: Execute bootstrap
        env:
          STRAP_DEBUG: 1
          # This enables iterating faster in the CI:
          # - Only install required libraries rather than brew bundle
          # - Skip updating Homebrew
          QUICK: 1
          # You can use this to test a different Sentry branch
          # CI_CHECKOUT_BRANCH: name_of_sentry_branch
        run: |
          ./bootstrap.sh

  slow-bootstrap:
    runs-on: macos-13
    timeout-minutes: 30
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: on
      # Make the environment more similar to what Mac defaults to
      SHELL: /bin/zsh

    steps:
      - uses: actions/checkout@v3

      # This will ensure that we test the sentry-cli and brew installation step
      - name: Uninstall brew & others
        run: |
          ./uninstall.sh

      - name: Execute bootstrap
        env:
          STRAP_DEBUG: 1
        run: |
          sudo chown "$USER" /usr/local
          ./bootstrap.sh

      # This is import for assuring engineers that they can run the code once
      # again if something where to fail
      - name: Second run
        run: |
          ./bootstrap.sh
