name: bootstrap
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bootstrap:
    runs-on: macos-latest
    timeout-minutes: 45
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: on
      # Make the environment more similar to what Mac defaults to
      SHELL: /bin/zsh

    steps:
      - uses: actions/checkout@v2

      - name: Execute bootstrap
        run: |
          ./bootstrap.sh

      # We can run a second time w/o anything breaking
      - name: Second run
        run: |
          ./bootstrap.sh
