name: bootstrap
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dev-env-cli:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v2

      - name: Execute bootstrap
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
          ./bootstrap.sh
