name: bootstrap
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fast-bootstrap:
    runs-on: macos-11
    timeout-minutes: 45
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: on
      # Make the environment more similar to what Mac defaults to
      SHELL: /bin/zsh

    steps:
      - uses: actions/checkout@v2

      - name: Execute bootstrap
        env:
          STRAP_DEBUG: 1
          # This enables iterating faster in the CI:
          # - Only install required libraries rather than brew bundle
          # - Skip updating Homebrew
          QUICK: 1
        run: |
          ./bootstrap.sh

      # We can run a second time w/o anything breaking
      - name: Second run
        run: |
          ./bootstrap.sh

  slow-bootstrap:
    runs-on: macos-11
    timeout-minutes: 45
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: on
      # Make the environment more similar to what Mac defaults to
      SHELL: /bin/zsh

    steps:
      - uses: actions/checkout@v2

      - name: Execute bootstrap
        env:
          STRAP_DEBUG: 1
        run: |
          ./bootstrap.sh

      # We can run a second time w/o anything breaking
      - name: Second run
        run: |
          ./bootstrap.sh
