name: linter
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'bootstrap.sh'
      - 'install-devenv.sh'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        pip install shellcheck-py==0.7.2.1
        shellcheck bootstrap.sh install-devenv.sh
